language: r
cache: packages

r_github_packages: PolMine/polmineR@dev

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.1


before_install:
  - Rscript -e 'install.packages("rmarkdown")'

r_packages:
  - shiny
  - shinyjs
  - miniUI


warnings_are_errors: true

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov(token = "26677b57-5e66-44cd-ad0c-49957456a028")'

