#' Create annolite htmlwidget
#' 
#' The HTML widget *annolite* is the core of the package and the `annolite()`
#' method is the constructor to generate it. The widget targets two
#' basic uses:
#' 1. The widget's *annotation mode* offers a pure R workflow for basic text
#' annotation tasks. In this scenario, it is used within a Shiny Gadget called
#' via `annotate()`.#
#' 2. The widget's *display mode* is designed to inspect the fulltext of a
#' document with highlighted annotations either in an interactive R session or
#' embedded in Rmarkdown documents. The widget's support of crosstalk enables
#' the interactive selection among a set of documents within an HTML document
#' generated from Rmarkdown.
#' 
#' @param x Either a `fulltexttable` object or an object that can be
#'   transformed to a `fulltexttable` using the `fulltexttable()` method.
#' @param annotations An optional `annotationstable` object. If supplied,
#'   existing annotations will be highlighted in the fulltext displayed.
#'   Defaults to an empty `annotationstable` generated by calling
#'   `annotationstable()`.
#' @param width The width of the annolite htmlwidget.
#' @param height The height of the annolite htmlwidget.
#' @param buttons Named `list` of length-one `character` vectors to specify
#'   labels of codes and colors that are assigned (names are codes, values
#'   colors).
#' @param box Length-one `logical` value, whether draw box around HTML widget
#'   with fulltext display.
#' @param group An identifier for a Crosstalk group. HTML widgets within one
#'   Crosstalk group can communicate with each other, see documentation of the
#'   argument `group` of `crosstalk::SharedData`. Defaults to "fulltext".
#' @param layout Relevant for crosstalk mode
#' @param crosstalk \code{logical}, whether to use crosstalk
#' @param ... Further arguments
#' @importFrom htmlwidgets createWidget sizingPolicy
#' @importFrom crosstalk crosstalkLibs is.SharedData bscols
#' @importFrom utils packageVersion
#' @export annolite
#' @aliases annolite-package annolite
#' @docType package
#' @name annolite
#' @rdname annolite
#' @examples 
#' library(polmineR)
#' sc <- corpus("GERMAPARLMINI") %>%
#'   subset(speaker == "Volker Kauder" & date == "2009-11-10")
#' tab <- fulltexttable(sc)
#' y <- annolite(
#'   x = tab, annotations = annotationstable(),
#'   width = "100%",
#'   buttons = list(keep = "yellow", drop = "orange")
#' )
#' @author Andreas Blaette
setGeneric("annolite", function(x, ...) standardGeneric("annolite"))

setOldClass("fulltexttable")

#' @rdname annolite
setMethod("annolite", "fulltexttable", function(x, annotations = annotationstable(), buttons = list(keep = "yellow", drop = "lightgreen"), width = "100%", height = NULL,  box = TRUE, crosstalk = FALSE, layout = "filter", group = "fulltext") {
  
  if (length(unique(x[["name"]])) == 1L){
    y <- createWidget(
      "annolite",
      package = "annolite",
      x = list(
        data = list(fulltext = htmlize(x), annotations = annotations),
        settings = list(
          annotationMode = TRUE,
          crosstalk = crosstalk,
          crosstalk_key = NULL,
          crosstalk_group = group,
          box = box,
          buttons = buttons
        )
      ),
      width = width,
      height = height,
      dependencies = list(
        htmltools::htmlDependency(
          name = "crosstalk", 
          version = packageVersion("crosstalk"),
          package = "crosstalk",
          src = "www",
          script = "js/crosstalk.min.js",
          stylesheet = "css/crosstalk.css"
        )
      ),
      sizingPolicy(
        browser.fill = TRUE,
        viewer.defaultHeight = 800L,
        browser.defaultHeight = 800L,
        viewer.fill = TRUE,
        knitr.figure = FALSE,
        knitr.defaultWidth = 800L,
        knitr.defaultHeight = 400L
      )
    )
  } else {
    x[["style"]] <- rep("display:none", times = nrow(x))
    x_sd <- crosstalk::SharedData$new(x, ~name, group = group) 
    if (layout == "filter"){
      y <- bscols(
        widths = c(3,9), device = "lg",
        crosstalk::filter_select(id = "select_text", label = "Selection", sharedData = x_sd, group = ~name, multiple = FALSE),
        htmlwidgets::createWidget(
          "annolite",
          package = "annolite",
          x = list(
            data = list(fulltext = htmlize(x), annotations = annotations),
            settings = list(
              annotationMode = FALSE,
              crosstalk = TRUE,
              box = box,
              crosstalk_key = "name",
              crosstalk_group = group
            )
          ),
          width = width, 
          height = height,
          dependencies = crosstalk::crosstalkLibs()
        )
      )
    } else {
      doc_datatable_sd <- DT::datatable(
        crosstalk::SharedData$new(data.frame(document_id = x[["name"]]), ~document_id, group = group),
        options = list(lengthChange = TRUE, pageLength = 8L, pagingType = "simple", dom = "tp"),
        rownames = NULL, width = "100%", selection = "single"
      )
      
      y <- bscols(
        widths = c(4,8),
        doc_datatable_sd,
        annolite(x_sd, annotations = annotations, width = width, height = height, box = box, crosstalk = TRUE)
      )
    }
  }
  y
})

setOldClass("SharedData")

#' @rdname annolite
#' @exportMethod annolite
setMethod("annolite", "SharedData", function(x, annotations = NULL, width = "100%", height = NULL, box = TRUE, group = x$groupName(), crosstalk = TRUE) {
  annolite(
    x = x$origData(),
    annotations = annotations,
    width = width, height = height, box = box,
    group = group, crosstalk = TRUE
  )
})


#' Render annolite htmlwidget in shiny apps.
#' 
#' @param outputId Output variable to read the value from.
#' @param width The width of the widget.
#' @param height The height of the widget.
#' @param expr An expression (...).
#' @param env The environment in which to evaluate expr.
#' @param quoted Is expr a quoted expression (with quote())? This is useful if
#'   you want to save an expression in a variable.
#' @export annoliteOutput
#' @importFrom htmlwidgets shinyWidgetOutput
#' @rdname shiny
annoliteOutput <- function(outputId, width = "100%", height = "100%") {
  shinyWidgetOutput(outputId, "annolite", width, height, package = "annolite")
}
#' @export renderAnnolite
#' @importFrom htmlwidgets shinyRenderWidget
#' @rdname shiny
renderAnnolite <- function(expr, env = parent.frame(), quoted = FALSE) {
  if (!quoted) { expr <- substitute(expr) } # force quoted
  shinyRenderWidget(expr, annoliteOutput, env, quoted = TRUE)
}


#' Sample annotation of a speech given by Volker Kauder
#' @rdname kauder_sample_annotation
"sample_annotation"

#' Jane Austen's novel Emma (tokenized)
#' 
#' The novels written by Jane Austen are popular data to illustrate text mining
#' applications readily available via the R package
#' [janeaustenr](https://CRAN.R-project.org/package=janeaustenr). To convey how
#' `annolite` may be used in the context of the tidytext approach (see [the book
#' by Julia Silge and David Robinson](https://www.tidytextmining.com/)), the
#' package includes a pre-processed object with the chapters of the novel Emma.
#' 
#' @format A `list`
#' @family datasets included in the annolite package
#' @rdname emma
"emma_chapters_tokenized"

#' Sample documents and annotations from the UN General Assembly
#' 
#' The package includes three pieces of data derived from the corpus of speeches
#' given in the UN General Assembly (UNGA corpus, [available at
#' Zenodo](https://zenodo.org/record/3831472#.X5nMp1kxlZ0)).
#' 
#' The file
#' [unga_topicmodelling.R](https://github.com/PolMine/annolite/blob/master/data-raw/unga_topicmodelling.R)
#' in the data-raw folder of the package has been used to create the data
#' objects.
#' 
#' @rdname undocs
#' @family datasets included in the annolite package
#' @format The object `secretary_general_2000` is a `fulltexttable`.
"secretary_general_2000"

#' @format The object `unga_migrationspeechess_fulltext` is a `fulltexttable` 
#' @rdname undocs
"unga_migrationspeeches_fulltext"

#' @format The object `unga_migrationspeeches_annotationstable` is an
#'   `annotationstable`.
#' @rdname undocs
"unga_migrationspeeches_anntationstable"
